.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PRIMETABLE" "1" "May 2013" "Guido Klingbeil" ""
Simple command line tool to print prime number multiplication tables\.
.
.P
Prime table prints the multiplication table of the first n prime numbers where n has to be > 2\.
.
.P
Features implemented * Compute primes with a multi\-threaded native C implementation of the Sieve of Erastosthenes using POSIX threads (pthreads), * Vectorisation of the inner most loop using SSE instructions, * Other prime generation algorithm just need to be implemented as a subclass of\. No further changes are necessary, we automatically find the new class using reflection, * Decorators implemented so far: \-adds headings to the table, \-colours the first row and column as well as
.
.IP "" 4
.
.nf

 the diagonal,
.
.fi
.
.IP "" 0
.
.IP "\(bu" 4
adds column and row seperators,
.
.IP "\(bu" 4
Accepts input from STDIN\.
.
.IP "" 0
.
.SH "Build Status"
To be done\.
.
.SH "Installation"
Add this line to your application\'s Gemfile:
.
.IP "" 4
.
.nf

$ bundle install

$ gem build primetable\.gemspec

$ gem install primetable \-\-no\-format\-executable
.
.fi
.
.IP "" 0
.
.P
Optional, run the unit tests:
.
.IP "" 4
.
.nf

$ bundle exec rspec spec
.
.fi
.
.IP "" 0
.
.P
Optional, run the behavioural tests:
.
.IP "" 4
.
.nf

$bundle exec cucumber features
.
.fi
.
.IP "" 0
.
.P
(Note: the tests require the development dependencies)
.
.SH "Help"
.
.nf

primetable \-\-help
gem man primetable

[RDoc](http://)
.
.fi
.
.SH "Usage"
.
.nf

Usage: primetable [options] [number_of_primes]

Options:
\-h, \-\-help                       Show command line help
\-c, \-\-colour                      Print a coloured table
\-l, \-\-label                      Print row and column labels
\-a, \-\-alg VAL                    Erastosthenes or Atkins sieve algorithm
    \-\-log\-level LEVEL            Set the logging level
                                 (debug|info|warn|error|fatal)
                                 (Default: info)
Examples

primetable            # prints a multiplication table of the first 10 primes
primetable 11         # prints out a table of the first 11 primes
echo 4 | primetable   # takes input argument from STDIN
.
.fi
.
.SH "Contributing"
.
.nf

1\. Fork it
2\. Create your feature branch (`git checkout \-b my\-new\-feature`)
3\. Commit your changes (`git commit \-am \'Added some feature\'`)
4\. Push to the branch (`git push origin my\-new\-feature`)
5\. Create new Pull Request
.
.fi

